### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by Mostafam-Taha** [Mostafam-Taha/Sahat-Al-llm#5]
قسم تحميل كتب PDF يعتمد على خورزمية **العد الثنائي** 

هذا  عنصر من عناصر قسم 
```html
<div class="download items-2">
            <div class="pdf-ra">
                <div class="pdf">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-wrench-adjustable-circle" viewBox="0 0 16 16"><path d="M12.496 8a4.5 4.5 0 0 1-1.703 3.526L9.497 8.5l2.959-1.11q.04.3.04.61"/><path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-1 0a7 7 0 1 0-13.202 3.249l1.988-1.657a4.5 4.5 0 0 1 7.537-4.623L7.497 6.5l1 2.5 1.333 3.11c-.56.251-1.18.39-1.833.39a4.5 4.5 0 0 1-1.592-.29L4.747 14.2A7 7 0 0 0 15 8m-8.295.139a.25.25 0 0 0-.288-.376l-1.5.5.159.474.808-.27-.595.894a.25.25 0 0 0 .287.376l.808-.27-.595.894a.25.25 0 0 0 .287.376l1.5-.5-.159-.474-.808.27.596-.894a.25.25 0 0 0-.288-.376l-.808.27z"/></svg>
                    <h2>فلسفة<span>-شرح</span></h2>
                    <p>شرح</p>
                    <a href="https://www.mediafire.com/file/uw55p5euz9oz2qi/%25D9%2581%25D9%2584%25D8%25B3%25D9%2581%25D8%25A9_-_%25D8%25B4%25D8%25B1%25D8%25AD_%25D8%25A7%25D9%2584%25D8%25B5%25D9%2581_%25D8%25A7%25D9%2584%25D8%25A7%25D9%2588%25D9%2584_%25D8%25A7%25D9%2584%25D8%25AB%25D8%25A7%25D9%2586%25D9%2588%25D9%258A_%25D8%25AA%25D8%25B1%25D9%2585_%25D8%25A7%25D9%2584%25D8%25A7%25D9%2588%25D9%2584_%25D8%25B3%25D8%25A7%25D8%25AD%25D8%25A9_%25D8%25A7%25D9%2584%25D8%25B9%25D9%2584%25D9%2585.pdf/file"><button class="Btn"><svg class="svgIcon"viewBox="0 0 384 512"height="1em"xmlns="http://www.w3.org/2000/svg"><path d="M169.4 470.6c12.5 12.5 32.8 12.5 45.3 0l160-160c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L224 370.8 224 64c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 306.7L54.6 265.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l160 160z"></path></svg><span class="icon2"></span><span class="tooltip">100MB</span></button></a>
                </div>
            </div>
        </div>
``` 

### يتم اظهار هذه العناصر عن طريق شريط البحث الاتي

```html
<div class="root-linge">
                <div class="search-bar">
                    <label for="search">
                        <input type="search" name="search" id="search" placeholder="بحث">
                    </label>
                </div>
                <div class="image-user">
                    <img src="image/516ce7c930e539f73ad36ed32fa4f9d7.jpg" alt="لا توجد صورة" loading="lazy">
                </div>
            </div>
``` 

###كود CSS 

```css

.input__container {
    position: relative;
    background: rgba(255, 255, 255, 0.664);
    padding: 10px 15px;
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 5px;
    border-radius: 22px;
    max-width: 300px;
    transition: transform 400ms;
    transform-style: preserve-3d;
    transform: rotateX(15deg) rotateY(-20deg);
    perspective: 500px;
}

.shadow__input {
    content: "";
    position: absolute;
    width: 100%;
    height: 100%;
    left: 0;
    bottom: 0;
    z-index: -1;
    filter: blur(30px);
    border-radius: 20px;
    background-color: #999cff;
    background-image: radial-gradient(at 85% 51%, hsla(60,60%,61%,1) 0px, transparent 50%),
        radial-gradient(at 74% 68%, hsla(235,69%,77%,1) 0px, transparent 50%),
        radial-gradient(at 64% 79%, hsla(284,72%,73%,1) 0px, transparent 50%),
        radial-gradient(at 75% 16%, hsla(283,60%,72%,1) 0px, transparent 50%),
        radial-gradient(at 90% 65%, hsla(153,70%,64%,1) 0px, transparent 50%),
        radial-gradient(at 91% 83%, hsla(283,74%,69%,1) 0px, transparent 50%),
        radial-gradient(at 72% 91%, hsla(213,75%,75%,1) 0px, transparent 50%);
}

.input__button__shadow {
    cursor: pointer;
    border: none;
    background: none;
    transition: transform 400ms, background 400ms;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 12px;
    padding: 5px;
}

.input__button__shadow:hover {
    background: rgba(255, 255, 255, 0.411);
}

.input__search {
    /* text-align: right; */
    width: 100%;
    border-radius: 20px;
    outline: none;
    border: none;
    padding: 8px;
    position: relative;
}
``` 

يتم رفع الملفات الخاصة بلكتب على 

<details><summary>Details</summary>
<p>

https://www.mediafire.com

</p>
</details>
