### ISSUE TITLE
تم حل المشكلة

### ISSUE THREAD

**Issue by Mostafam-Taha** [Mostafam-Taha/Sahat-Al-llm#9]
لقد تم حل المشكلة التي تظهر عندما يتم تحميل الصفحة

```html
<!DOCTYPE html>
<html lang="ar">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="icon" href="image/logo/book-open-reader-solid.svg" type="image/svg">
    <link rel="stylesheet" href="css/style.css">    
    <link rel="stylesheet" href="CSS/PDF.css">
    <link rel="stylesheet" href="CSS/Dark Mode.css">
    <title>Sahat Al-llm | PDF</title>
</head>
<body>
    <div class="header-op">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-list menu-icon" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
        </svg>
        <a href="index.html">
            <div class="br-logo">
                <svg class="logo-sahat-alllm" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path fill="#183153" d="M160 96a96 96 0 1 1 192 0A96 96 0 1 1 160 96zm80 152l0 264-48.4-24.2c-20.9-10.4-43.5-17-66.8-19.3l-96-9.6C12.5 457.2 0 443.5 0 427L0 224c0-17.7 14.3-32 32-32l30.3 0c63.6 0 125.6 19.6 177.7 56zm32 264l0-264c52.1-36.4 114.1-56 177.7-56l30.3 0c17.7 0 32 14.3 32 32l0 203c0 16.4-12.5 30.2-28.8 31.8l-96 9.6c-23.2 2.3-45.9 8.9-66.8 19.3L272 512z"/></svg>
                <h1>Sahat Al-llm</h1>
            </div>
        </a>
    </div>
    <!-- Header -->
    <header class="header">
        <nav class="navbar">
            <a href="index.html">
                <div class="logo">
                        <svg class="logo-sahat-alllm" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path fill="#183153" d="M160 96a96 96 0 1 1 192 0A96 96 0 1 1 160 96zm80 152l0 264-48.4-24.2c-20.9-10.4-43.5-17-66.8-19.3l-96-9.6C12.5 457.2 0 443.5 0 427L0 224c0-17.7 14.3-32 32-32l30.3 0c63.6 0 125.6 19.6 177.7 56zm32 264l0-264c52.1-36.4 114.1-56 177.7-56l30.3 0c17.7 0 32 14.3 32 32l0 203c0 16.4-12.5 30.2-28.8 31.8l-96 9.6c-23.2 2.3-45.9 8.9-66.8 19.3L272 512z"/></svg>
                    <h1>Sahat Al-llm</h1>
                </div>
            </a>
                <ul>
                <li><a href="index.html">الرئسية</a></li>
                <li><a href="course.html">دروسي</a></li>
                <li><a href="#">الكتب</a></li>
                <li><a href="#">Element</a></li>
                <li><a href="#">Element</a></li>
            </ul>
            <div class="root-linge">
                <div class="search-bar">
                    <label for="search">
                        <input type="search" name="search" id="search" placeholder="بحث">
                    </label>
                </div>
                <div class="image-user">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16" id="toggle-user"><path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/><path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/></svg>
                </div>
            </div>
        </nav>
    </header>
    <!-- View User -->
    <div class="view-user" id="user-box">
        <div class="container">
            <div class="username-profile">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16"><path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/><path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/></svg>
                <div class="br-username">
                    <h3>User Name</h3>
                    <p>Email</p>
                </div>
            </div>
            <hr class="hr-username">
            <div class="option-profile">
                <ul>
                    <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16"><path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z"/></svg><a href="#">الملف الشخصي</a></li>
                    <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-easel" viewBox="0 0 16 16"><path d="M8 0a.5.5 0 0 1 .473.337L9.046 2H14a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-1.85l1.323 3.837a.5.5 0 1 1-.946.326L11.092 11H8.5v3a.5.5 0 0 1-1 0v-3H4.908l-1.435 4.163a.5.5 0 1 1-.946-.326L3.85 11H2a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h4.954L7.527.337A.5.5 0 0 1 8 0M2 3v7h12V3z"/></svg><a href="#">الدورات</a></li>
                    <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book-half" viewBox="0 0 16 16"><path d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/></svg><a href="#">الكتب</a></li>
                    <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16"><path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492M5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0"/><path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115z"/></svg><a href="#">الإعدادات</a></li>
                    <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-question-circle" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/><path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286m1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94"/></svg><a href="#">المساعدة</a></li>
                </ul>
            </div>
            <hr class="hr-username">
            <div class="fast-option">
                <ul>
                    <li>
                        <div class="dark-light">
                            <div class="line-setting-mode"></div>
                            <div class="line-setting-mode-2"></div>
                            <div style="cursor: pointer; display: inline;">Mode<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-highlights" viewBox="0 0 16 16"><path d="M16 8A8 8 0 1 0 0 8a8 8 0 0 0 16 0m-8 5v1H4.5a.5.5 0 0 0-.093.009A7 7 0 0 1 3.1 13zm0-1H2.255a7 7 0 0 1-.581-1H8zm-6.71-2a7 7 0 0 1-.22-1H8v1zM1 8q0-.51.07-1H8v1zm.29-2q.155-.519.384-1H8v1zm.965-2q.377-.54.846-1H8v1zm2.137-2A6.97 6.97 0 0 1 8 1v1z"/></svg></div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="overlay" id="overlay"></div>
    <!-- Courses -->
    <section class="you-learn-course">
        <div class="container">
            <div class="str">
                <div class="img-cor-one">
                    <img src="image/element/category-1.svg" alt="لا توجد صورة" loading="lazy">
                </div>
                <div class="text-ari">
                    <h1>أختر الصف الدراسي</h1>
                    <div class="btn-ari">
                        <button class="animated-button" onclick="navigateToPage('PDF/secondary 2.html')"><svg viewBox="0 0 24 24" class="arr-2" xmlns="http://www.w3.org/2000/svg"><path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path></svg><span class="text">الصف الثاني الثانوي</span><span class="circle"></span><svg viewBox="0 0 24 24" class="arr-1" xmlns="http://www.w3.org/2000/svg"><path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path></svg></button>
                        <button class="animated-button" onclick="navigateToPage('PDF/secondary 1.html')"><svg viewBox="0 0 24 24" class="arr-2" xmlns="http://www.w3.org/2000/svg"><path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path></svg><span class="text">الصف الاول الثانوي</span><span class="circle"></span><svg viewBox="0 0 24 24" class="arr-1" xmlns="http://www.w3.org/2000/svg"><path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path></svg></button>
                    </div>
                </div>
                <div class="img-cor-one">
                    <img src="image/element/category-2.svg" alt="لا توجد صورة" loading="lazy">
                </div>
            </div>
        </div>
    </section>
    <!-- Loading Screen -->
    <div id="loading-screen">
        <div class="loader"></div>
        <div aria-label="Orange and tan hamster running in a metal wheel" role="img" class="wheel-and-hamster">
            <div class="wheel"></div>
            <div class="hamster">
                <div class="hamster__body">
                    <div class="hamster__head">
                        <div class="hamster__ear"></div>
                        <div class="hamster__eye"></div>
                        <div class="hamster__nose"></div>
                    </div>
                    <div class="hamster__limb hamster__limb--fr"></div>
                    <div class="hamster__limb hamster__limb--fl"></div>
                    <div class="hamster__limb hamster__limb--br"></div>
                    <div class="hamster__limb hamster__limb--bl"></div>
                    <div class="hamster__tail"></div>
                </div>
            </div>
            <div class="spoke"></div>
        </div>
    </div>
    <script src="js/PDF.js"></script>
    <script src="js/script.js"></script>
    <script src="js/light-dark-mode.js"></script>
    <!-- <script src="js/look login.js"></script> -->
    <script>
        // تحديد الأيقونة والهيدر
        const menuIcon = document.querySelector('.menu-icon');
            const header = document.querySelector('.header');
    
            // إضافة حدث الضغط على الأيقونة
            menuIcon.addEventListener('click', (event) => {
            header.classList.toggle('show'); // إظهار أو إخفاء الهيدر
            event.stopPropagation(); // منع الحدث من الوصول إلى العناصر الأخرى
            });
    
            // إضافة حدث الضغط على المستند
            document.addEventListener('click', (event) => {
            // التحقق إذا كان العنصر المضغوط عليه ليس الهيدر أو الأيقونة
            if (!header.contains(event.target) && !menuIcon.contains(event.target)) {
                header.classList.remove('show'); // إخفاء الهيدر
            }
        });

        function navigateToPage(pageUrl) {
            window.location.href = pageUrl;
        }
    </script>
</body>
</html>

```

**Comment by Mostafam-Taha** [comment]
```CSS
:root {
    --bs-primary-color: #ffffff;
    --bs-secondary-color: rgba(214, 41, 62, 0.1);
    --fc-background-color-1: #f7c32e26;
    --fc-background-color-2: #1d3b531a;
    --fc-background-color-3: #6f42c11a;
    --fc-background-color-4: #17a2b81a;
    --fc-background-color-5: #0cbc871a;
    --fc-btn-bg: #066ac9;
    --fc-btn-bg-co: #001e2b;
    --fc-color-btn-new: #d6293e!important;
    --fc-inp-border-co: #dfe2e1;
    --fo-h1-h6-co: #21313c;
    --fc-p-co: #5f5f5f;
    --fc-par-color: #ffc107!important;
    --fc-prod-sale-color: #db3030!important;
    --fc-cursor-poi: pointer;
    --fc-margin-width: 0 100px;
    --fc-padding-width-btn: 7px 22px;
    --fc-border-color: #dfe2e1;
    --fc-border-width-none: none;
    --fc-border-width: 1px;
    --fc-border-style: solid;
    --fc-border-co-hevor: #066ac9;
    --fc-border-radius-width: 7px;
    --fc-box-shadow-hevor: 0px 0px 0px 5px #066bc954;
}

.row {
    --fc-breakpoint-labtop-L: 1440px;
    --fc-breakpoint-laptop: 1024px;
    --fc-breakpoint-md: ;
    --fc-breakpoint-lg: ;
    --fc-breakpoint-xl: ;
    --fc-breakpoint-xxl: ;
}

* {
    font-family: "Noto Kufi Arabic", sans-serif;
    font-family: 'Cairo', sans-serif;
}

html {
    scroll-behavior: smooth;
}

body {
    font-family: "Noto Kufi Arabic", sans-serif;
    font-family: 'Cairo', sans-serif;
    background-color: var(--bs-primary-color);
    color: var(--fo-h1-h6-co);
    margin: 0;
    padding: 0;
}


body::-webkit-scrollbar {
    display: none;
}

h1, h2, h3, h4, h5, h6 {
    font-family: 'Cairo', sans-serif;
    color: var(--fo-h1-h6-co);
    margin: 0;
    padding: 0;
}

p {
    font-family: 'Cairo', sans-serif;
    margin: 0;
    padding: 0;
}

a {
    font-family: 'Cairo', sans-serif;
    text-decoration: var(--fc-border-width-none);
    color: var(--fc-p-co);
}

hr {
    margin: 35px 0;
    border: var(--fc-border-width-none);
    background-color: var(--fc-inp-border-co);
    width: 100%;
    height: 1px;
}

/* Style Courses */
.you-learn-course {
    margin: var(--fc-margin-width);
}

.you-learn-course .container {
    margin: 70px 0;
}

.you-learn-course .container .str {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.you-learn-course .container .str .text-ari {
    text-align: center;
}

.you-learn-course .container .str .text-ari h1 {
    font-size: 38px;
    font-weight: 500;
}

.you-learn-course .container .str .text-ari p {
    font-size: 15px;
    font-weight: 400;
    color: var(--fc-p-co);
    margin: 7.5px 0 0 0;
}

.you-learn-course .container .str .inp-search-course{
    margin: 20px 0 0 0;
}

.input__container {
    position: relative;
    background: rgba(255, 255, 255, 0.664);
    padding: 10px 15px;
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 5px;
    border-radius: 22px;
    max-width: 300px;
    transition: transform 400ms;
    transform-style: preserve-3d;
    transform: rotateX(15deg) rotateY(-20deg);
    perspective: 500px;
}

.shadow__input {
    content: "";
    position: absolute;
    width: 100%;
    height: 100%;
    left: 0;
    bottom: 0;
    z-index: -1;
    filter: blur(30px);
    border-radius: 20px;
    background-color: #999cff;
    background-image: radial-gradient(at 85% 51%, hsla(60,60%,61%,1) 0px, transparent 50%),
        radial-gradient(at 74% 68%, hsla(235,69%,77%,1) 0px, transparent 50%),
        radial-gradient(at 64% 79%, hsla(284,72%,73%,1) 0px, transparent 50%),
        radial-gradient(at 75% 16%, hsla(283,60%,72%,1) 0px, transparent 50%),
        radial-gradient(at 90% 65%, hsla(153,70%,64%,1) 0px, transparent 50%),
        radial-gradient(at 91% 83%, hsla(283,74%,69%,1) 0px, transparent 50%),
        radial-gradient(at 72% 91%, hsla(213,75%,75%,1) 0px, transparent 50%);
}

.input__button__shadow {
    cursor: pointer;
    border: none;
    background: none;
    transition: transform 400ms, background 400ms;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 12px;
    padding: 5px;
}

.input__button__shadow:hover {
    background: rgba(255, 255, 255, 0.411);
}

.input__search {
    /* text-align: right; */
    width: 100%;
    border-radius: 20px;
    outline: none;
    border: none;
    padding: 8px;
    position: relative;
}

/* Style Choose-a-Categories */
.choose-a-categories {
    margin: var(--fc-margin-width);
}
.choose-a-categories  {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 10px;
}

.choose-a-categories .pdf-ra .pdf,
.choose-a-categories .download {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    border-radius: var(--fc-border-radius-width);
    padding: 5px 0 5px 0;
    transition: transform 0.5s;
    cursor: var(--fc-cursor-poi);
}

.choose-a-categories .items-1 {
    background-color: var(--fc-background-color-1);
}

.choose-a-categories .items-2 {
    background-color: var(--fc-background-color-2);
}

.choose-a-categories .items-3 {
    background-color: var(--fc-background-color-3);
}

.choose-a-categories .items-4 {
    background-color: var(--fc-background-color-4);
}

.choose-a-categories .items-5 {
    background-color: var(--fc-background-color-5);
}

.choose-a-categories .items-1:hover,
.items-2:hover,
.items-3:hover,
.items-4:hover,
.items-5:hover{
    transform: scale(1.02);
}

.choose-a-categories .download svg {
    width: 36px;
    height: 36px;
}

.Btn {
    margin: 20px 0 0 0;
    padding: 10px;
    width: 50px;
    height: 50px;
    border: none;
    border-radius: 50%;
    background-color: rgb(255, 255, 255);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    position: relative;
    transition-duration: 0.3s;
}
  
.svgIcon {
    fill: var(--fc-btn-bg);
}
  
.icon2 {
    width: 18px;
    height: 5px;
    border-bottom: 2px solid var(--fc-btn-bg);
    border-left: 2px solid var(--fc-btn-bg);
    border-right: 2px solid var(--fc-btn-bg);
}
  
.tooltip {
    position: absolute;
    top: -50px;
    opacity: 0;
    background-color: rgb(12, 12, 12);
    color: rgb(255, 255, 255);
    padding: 10px 10px;
    border-radius: 5px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition-duration: 0.2s;
    pointer-events: none;
    letter-spacing: 0.5px;
}

.tooltip::before {
    position: absolute;
    content: "";
    width: 10px;
    height: 10px;
    background-color: rgb(12, 12, 12);
    background-size: 1000%;
    background-position: center;
    transform: rotate(45deg);
    bottom: -5%;
    transition-duration: 0.3s;
}

.Btn:hover .tooltip {
    opacity: 1;
    transition-duration: 0.3s;
}

.Btn:hover {
    background-color: var(--fc-btn-bg-co);
    transition-duration: 0.3s;
}

.Btn:hover .icon2 {
    border-bottom: 2px solid white;
    border-left: 2px solid white;
    border-right: 2px solid white;
}

.Btn:hover .svgIcon {
    fill: white;
    animation: slide-in-top 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.btn-ari {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    align-items: center;
    justify-content: center;
    margin: 20px 0 0 0;
    gap: 20px;
} 

.animated-button {
    position: relative;
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 10px 30px;
    border: 4px solid;
    border-color: transparent;
    font-size: 14px;
    background-color: inherit;
    border-radius: 100px;
    font-weight: 500;
    color: greenyellow;
    box-shadow: 0 0 0 2px greenyellow;
    cursor: pointer;
    overflow: hidden;
    transition: all 0.6s cubic-bezier(0.23, 1, 0.32, 1);
}
  
.animated-button svg {
    position: absolute;
    width: 24px;
    fill: greenyellow;
    z-index: 9;
    transition: all 0.8s cubic-bezier(0.23, 1, 0.32, 1);
}
  
.animated-button .arr-1 {
    right: 16px;
}
  
.animated-button .arr-2 {
    left: -25%;
}
  
.animated-button .circle {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 20px;
    height: 20px;
    background-color: greenyellow;
    border-radius: 50%;
    opacity: 0;
    transition: all 0.8s cubic-bezier(0.23, 1, 0.32, 1);
}
  
.animated-button .text {
    position: relative;
    z-index: 1;
    color: var(--fc-p-co);
    transform: translateX(-12px);
    transition: all 0.8s cubic-bezier(0.23, 1, 0.32, 1);
}
  
.animated-button:hover {
    box-shadow: 0 0 0 12px transparent;
    color: #212121;
    border-radius: 12px;
}
  
.animated-button:hover .arr-1 {
    right: -25%;
}
  
.animated-button:hover .arr-2 {
    left: 16px;
}
  
.animated-button:hover .text {
    transform: translateX(12px);
}
  
.animated-button:hover svg {
    fill: #212121;
}
  
.animated-button:active {
    scale: 0.95;
    box-shadow: 0 0 0 4px greenyellow;
}
  
.animated-button:hover .circle {
    width: 220px;
    height: 220px;
    opacity: 1;
}  

@keyframes slide-in-top {
    0% {
        transform: translateY(-10px);
        opacity: 0;
    }

    100% {
        transform: translateY(0px);
        opacity: 1;
    }
}

/* Style Emulation */
@media (max-width: 1024px) {
    .you-learn-course {
        margin: 50px 50px;
    }

    .you-learn-course .container .str .text-ari h1,
    .choose-a-categories .container .text-choose h1 {
        font-size: 30px;
    }

    .you-learn-course .container .str .text-ari p,
    .choose-a-categories .container .text-choose p {
        font-size: 13px;
    }

    .you-learn-course .container .str .inp-search-course {
        margin: 10px 0 0 0;
    }

    .you-learn-course .container .str .img-cor-one img {
        width: 95%;
    }

    .choose-a-categories {
        margin: 0 50px 50px 50px;
    }

    .choose-a-categories .container .choose .items-1,
    .choose .items-2,
    .choose .items-3,
    .choose .items-4,
    .choose .items-5 {
        padding: 15px;
    }

    .choose-a-categories .container .choose .items-1 svg {
        width: 30px;
        height: 30px;
    }
}

@media (max-width: 768px) {
    .you-learn-course {
        margin: 50px 20px;
    }

    .you-learn-course .container .str .text-ari h1,
    .choose-a-categories .container .text-choose h1 {
        font-size: 25px;
    }

    .you-learn-course .container .str .text-ari p,
    .choose-a-categories .container .text-choose p {
        font-size: 12px;
    }

    .you-learn-course .container .str .inp-search-course {
        margin: 10px 0 0 0;
    }

    .you-learn-course .container .str .img-cor-one img {
        width: 90%;
    }

    .choose-a-categories {
        margin: 0 20px 50px 20px;
    }

    .choose-a-categories {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 10px;
    }

    .choose-a-categories .container .choose .items-1,
    .choose .items-2,
    .choose .items-3,
    .choose .items-4,
    .choose .items-5 {
        padding: 15px;
    }

    .choose-a-categories .container .choose .items-1 svg {
        width: 30px;
        height: 30px;
    }
}

@media (max-width: 425px) {
    .you-learn-course {
        margin: 50px 10px;
    }

    .you-learn-course .container .str .text-ari h1,
    .choose-a-categories .container .text-choose h1 {
        font-size: 20px;
    }

    .you-learn-course .container .str .text-ari p,
    .choose-a-categories .container .text-choose p {
        font-size: 10px;
        max-width: 200px;
        text-align: center;
        display: flex;
        align-items: center;
    }

    .you-learn-course .container .str .inp-search-course {
        margin: 25px 0 0 0;
    }

    .you-learn-course .container .str .img-cor-one img {
        display: var(--fc-border-width-none);
    }

    .choose-a-categories {
        margin: 0 10px 50px 10px;
    }

    .choose-a-categories {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
    }

    .choose-a-categories .items-1,
    .choose .items-2,
    .choose .items-3,
    .choose .items-4,
    .choose .items-5 {
        padding: 15px;
    }

    .choose-a-categories .items-1 svg {
        width: 30px;
        height: 30px;
    }
}

@media (max-width: 375px) {
    .you-learn-course {
        margin: 50px 10px;
    }

    .you-learn-course .container .str .text-ari h1,
    .choose-a-categories .container .text-choose h1 {
        font-size: 18px;
    }

    .you-learn-course .container .str .text-ari p,
    .choose-a-categories .container .text-choose p {
        font-size: 9px;
    }

    .you-learn-course .container .str .inp-search-course {
        margin: 25px 0 0 0;
    }

    .you-learn-course .container .str .img-cor-one img {
        display: var(--fc-border-width-none);
    }

    .choose-a-categories {
        margin: 0 10px 50px 10px;
    }

    .choose-a-categories {
        display: grid;
        grid-template-columns: repeat(1, 1fr);
        gap: 10px;
    }

    .choose-a-categories .items-1,
    .choose .items-2,
    .choose .items-3,
    .choose .items-4,
    .choose .items-5 {
        padding: 15px;
    }

    .choose-a-categories .items-1 svg {
        width: 30px;
        height: 30px;
    }
}

@media (max-width: 320px) {
    .you-learn-course {
        margin: 50px 10px;
    }

    .you-learn-course .container .str .text-ari h1,
    .choose-a-categories .container .text-choose h1 {
        font-size: 16px;
    }

    .you-learn-course .container .str .text-ari p,
    .choose-a-categories .container .text-choose p {
        font-size: 8px;
    }

    .you-learn-course .container .str .inp-search-course {
        margin: 25px 0 0 0;
    }

    .you-learn-course .container .str .img-cor-one img {
        display: var(--fc-border-width-none);
    }

    .choose-a-categories {
        margin: 0 10px 50px 10px;
    }

    .choose-a-categories .container .choose {
        display: grid;
        grid-template-columns: repeat(1, 1fr);
        gap: 10px;
    }

    .choose-a-categories .items-1,
    .choose .items-2,
    .choose .items-3,
    .choose .items-4,
    .choose .items-5 {
        padding: 15px;
    }

    .choose-a-categories .items-1 svg {
        width: 30px;
        height: 30px;
    }
}
```
